name: TrawelWithTimo
favicon: null
layout_spectrum: 0.00137
typography_spectrum: 0.23243
title: Travel with Timo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f1f1ef'
    - '#8b8683'
    - '#54dafd'
    - '#007ab5'
  brandStrength: 0
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
